site_name: Java Studies and Algo play ground
repo_url: https://github.com/jbcodeforce/Java-studies
nav:
  - Introduction: index.md
  - Microprofile 3.x: microprofile.md
  - Open Liberty: openliberty.md
  - Quarkus: quarkus.md
  - Vert.x: vertx.md
  - Concurrency : concurrent.md
  - MQ challenge: mqChallenge.md
  - Java FAQ: FAQ.md
  - VScode: java-vscode.md
  - Compendium: compendium.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences